services:
  mysql-server:
    image: mysql:8.4.6
    ports:
      - ${HOST_DB_PORT}:${BD_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${BD_ROOT_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./app/database/data:/var/lib/mysql

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./app/database/sql:/flyway/sql
    command: -url=jdbc:mysql://${BD_HOST}:${BD_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} -connectRetries=10 migrate